import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#c6955e",
        "on-surface-variant": "#43474e",
        "on-tertiary": "#ffffff",
        "on-background": "#1a1c1e",
        "outline": "#74777f",
        "secondary-container": "#7db6ff",
        "on-surface": "#1a1c1e",
        "primary-fixed-dim": "#adc7f7",
        "background": "#faf9fd",
        "inverse-surface": "#2f3033",
        "secondary-fixed-dim": "#a2c9ff",
        "inverse-primary": "#adc7f7",
        "on-tertiary-fixed": "#2b1700",
        "tertiary-fixed-dim": "#f2bc82",
        "tertiary": "#321b00",
        "on-error": "#ffffff",
        "surface-container-highest": "#e3e2e6",
        "on-tertiary-fixed-variant": "#633f0f",
        "surface-container-low": "#f4f3f7",
        "surface-container-high": "#e9e7eb",
        "on-primary-fixed": "#001b3c",
        "tertiary-container": "#4f2e00",
        "surface-dim": "#dad9dd",
        "on-primary-fixed-variant": "#2d476f",
        "on-secondary-container": "#00477f",
        "surface": "#faf9fd",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#001c38",
        "surface-variant": "#e3e2e6",
        "secondary-fixed": "#d3e4ff",
        "on-primary": "#ffffff",
        "primary-fixed": "#d6e3ff",
        "surface-tint": "#455f88",
        "outline-variant": "#c4c6cf",
        "primary": "#002045",
        "inverse-on-surface": "#f1f0f4",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#004881",
        "tertiary-fixed": "#ffddba",
        "surface-container": "#efedf1",
        "error-container": "#ffdad6",
        "primary-container": "#1a365d",
        "surface-bright": "#faf9fd",
        "secondary": "#1960a3",
        "on-primary-container": "#86a0cd",
        // Semantic aliases
        "success": "#319795",
        "warning": "#d97706",
        "info": "#1960a3",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "gutter": "16px",
        "margin": "24px",
        "unit": "4px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "h1": ["30px", { lineHeight: "38px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "h2": ["24px", { lineHeight: "32px", fontWeight: "600", letterSpacing: "-0.01em" }],
        "h3": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      boxShadow: {
        "card": "0 2px 12px rgba(0,0,0,0.04)",
        "card-hover": "0 4px 20px rgba(0,0,0,0.08)",
        "overlay": "0 8px 32px rgba(26,54,93,0.15)",
        "float": "0 4px 12px rgba(26,54,93,0.08)",
      },
      animation: {
        "fade-in": "fadeIn 0.2s ease-in-out",
        "slide-in": "slideIn 0.3s ease-out",
        "pulse-dot": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(4px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideIn: {
          "0%": { opacity: "0", transform: "translateX(-8px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
