"""add attachments table

Revision ID: 082e64e101f4
Revises: 559f2f2a2384
Create Date: 2026-05-11 15:05:03.809335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '082e64e101f4'
down_revision: Union[str, None] = '559f2f2a2384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('entityType', sa.String(length=50), nullable=False),
    sa.Column('entityId', sa.String(length=25), nullable=False),
    sa.Column('originalName', sa.String(length=300), nullable=False),
    sa.Column('storedName', sa.String(length=300), nullable=False),
    sa.Column('mimeType', sa.String(length=100), nullable=False),
    sa.Column('fileSize', sa.Integer(), nullable=False),
    sa.Column('uploadedById', sa.String(length=25), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploadedById'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachment_entity', 'attachments', ['entityType', 'entityId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attachment_entity', table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
