"""add services table

Revision ID: 559f2f2a2384
Revises: 
Create Date: 2026-05-11 14:35:28.254729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '559f2f2a2384'
down_revision: Union[str, None] = '0000000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('defaultPrice', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('branchId', sa.String(length=25), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branchId'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('insurance_claims')
    op.drop_table('consent_forms')
    op.drop_table('patient_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_documents',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('patientId', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('fileUrl', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('fileSize', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mimeType', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('notes', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('uploadedById', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('uploadedAt', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['patientId'], ['patients.id'], name='patient_documents_patientId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('consent_forms',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('patientId', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('formType', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('formVersion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('signedAt', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('signatureUrl', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('witnessId', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('isValid', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['patientId'], ['patients.id'], name='consent_forms_patientId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('insurance_claims',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('invoiceId', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('providerId', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('claimNumber', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('submittedAt', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('approvedAmount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('rejectionReason', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('resubmittedAt', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('paidAt', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('documents', mysql.JSON(), nullable=False),
    sa.Column('notes', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(fsp=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('services')
    # ### end Alembic commands ###
